# Generated by Django 4.2.4 on 2023-10-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruitz', '0002_producto_color_producto_tamaño_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
