# Generated by Django 4.2.4 on 2023-10-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruitz', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
