# Generated by Django 4.2.4 on 2023-10-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruitz', '0008_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, to='ruitz.color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaños',
            field=models.ManyToManyField(blank=True, to='ruitz.tamaño'),
        ),
    ]
