# Generated by Django 4.2.4 on 2023-10-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruitz', '0009_remove_producto_color_remove_producto_tamaño_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tamaños',
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruitz.tamaño'),
        ),
    ]
